Update jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -34,6 +34,12 @@ pipeline {
             }
         }
 
+        stage('Debug: Print Bandit Report') {
+            steps {
+                echo 'Contents of bandit_report.json:'
+                sh 'cat bandit_report.json || echo "bandit_report.json not found or empty"'
+            }
+        }
         stage('Security: Dependency Scan') {
             steps {
                 echo 'Running Dependency Vulnerability Scan with Safety...'
@@ -55,13 +61,6 @@ pipeline {
                 archiveArtifacts artifacts: 'cfn_nag_report.json', fingerprint: true
             }
         }
-        stage('Debug: Print Safety Report') {
-            steps {
-                echo 'Contents of safety_report.json:'
-                sh 'cat safety_report.json || echo "safety_report.json not found or empty"'
-            }
-        }
-
         stage('Security: Evaluate Reports') {
             steps {
                 script {
@@ -90,15 +89,10 @@ pipeline {
                     // Evaluate Safety Report
                     if (fileExists('safety_report.json')) {
                         def safetyReport = readJSON file: 'safety_report.json'
-                        def vulnerabilities = safetyReport.vulnerabilities ?: []
-                        if (vulnerabilities.size() > 0) {
-                            echo "Found ${vulnerabilities.size()} vulnerable dependencies."
+                        if (safetyReport.issues.size() > 0) {
+                            echo 'Vulnerable dependencies found.'
                             failBuild = true
-                        } else {
-                            echo 'No vulnerable dependencies found.'
                         }
-                    } else {
-                        echo 'safety_report.json not found.'
                     }
         
                     // Evaluate cfn-nag Report
